// file: app/money/debts/mock-data.ts
// Mock data for Loans and IOUs

import { Loan, LoanPayment, IOU } from "@/types/finance";

export const mockLoans: Loan[] = [
  {
    id: "loan_001",
    name: "Home Loan - Astrum Ampang",
    bankName: "AmBank Islamic",
    type: "HOME",
    totalAmount: 450000,
    remainingBalance: 387500,
    monthlyInstalment: 2250,
    tenureMonths: 300, // 25 years
    startedOn: "2022-06-01",
    status: "IN_ARREARS",
    nextPaymentDate: "2026-01-05",
    tags: ["property", "astrum"],
    progressPercent: 13.9,
    hasArrears: true,
  },
  {
    id: "loan_002",
    name: "Car Loan - Honda Civic",
    bankName: "Maybank",
    type: "CAR",
    totalAmount: 85000,
    remainingBalance: 52300,
    monthlyInstalment: 1420,
    tenureMonths: 84, // 7 years
    startedOn: "2023-03-15",
    status: "ACTIVE",
    nextPaymentDate: "2026-01-15",
    tags: ["car", "honda"],
    progressPercent: 38.5,
    hasArrears: false,
  },
  {
    id: "loan_003",
    name: "Personal Loan - Emergency",
    bankName: "CIMB",
    type: "PERSONAL",
    totalAmount: 15000,
    remainingBalance: 8200,
    monthlyInstalment: 650,
    tenureMonths: 36, // 3 years
    startedOn: "2024-02-01",
    status: "ACTIVE",
    nextPaymentDate: "2026-01-01",
    tags: ["emergency", "personal"],
    progressPercent: 45.3,
    hasArrears: false,
  },
];

export const mockLoanPaymentsByLoanId: Record<string, LoanPayment[]> = {
  loan_001: [
    {
      id: "payment_001",
      loanId: "loan_001",
      transactionId: "txn_123",
      date: "2025-12-05",
      paidAmount: 2250,
      principalPortion: 1687.5,
      interestPortion: 562.5,
      lateCharges: 0,
      otherCharges: 0,
      isExtraPayment: false,
      isArrearsPayment: false,
      runningBalanceAfter: 389750,
      notes: "Regular monthly payment",
    },
    {
      id: "payment_002",
      loanId: "loan_001",
      transactionId: "txn_124",
      date: "2025-11-05",
      paidAmount: 2250,
      principalPortion: 1680.0,
      interestPortion: 570.0,
      lateCharges: 0,
      otherCharges: 0,
      isExtraPayment: false,
      isArrearsPayment: false,
      runningBalanceAfter: 392000,
      notes: "Regular monthly payment",
    },
    {
      id: "payment_003",
      loanId: "loan_001",
      transactionId: "txn_125",
      date: "2025-10-12",
      paidAmount: 3500,
      principalPortion: 1200.0,
      interestPortion: 550.0,
      lateCharges: 150,
      otherCharges: 50,
      isExtraPayment: false,
      isArrearsPayment: true,
      runningBalanceAfter: 394250,
      notes: "Arrears payment - late by 7 days",
    },
    {
      id: "payment_004",
      loanId: "loan_001",
      transactionId: "txn_126",
      date: "2025-09-05",
      paidAmount: 5000,
      principalPortion: 4325.0,
      interestPortion: 675.0,
      lateCharges: 0,
      otherCharges: 0,
      isExtraPayment: true,
      isArrearsPayment: false,
      runningBalanceAfter: 395450,
      notes: "Extra payment - bonus month",
    },
    {
      id: "payment_005",
      loanId: "loan_001",
      transactionId: "txn_127",
      date: "2025-08-05",
      paidAmount: 2250,
      principalPortion: 1665.0,
      interestPortion: 585.0,
      lateCharges: 0,
      otherCharges: 0,
      isExtraPayment: false,
      isArrearsPayment: false,
      runningBalanceAfter: 399775,
      notes: "Regular monthly payment",
    },
  ],
  loan_002: [
    {
      id: "payment_006",
      loanId: "loan_002",
      transactionId: "txn_201",
      date: "2025-12-15",
      paidAmount: 1420,
      principalPortion: 1150.0,
      interestPortion: 270.0,
      lateCharges: 0,
      otherCharges: 0,
      isExtraPayment: false,
      isArrearsPayment: false,
      runningBalanceAfter: 53720,
      notes: "Regular monthly payment",
    },
    {
      id: "payment_007",
      loanId: "loan_002",
      transactionId: "txn_202",
      date: "2025-11-15",
      paidAmount: 1420,
      principalPortion: 1145.0,
      interestPortion: 275.0,
      lateCharges: 0,
      otherCharges: 0,
      isExtraPayment: false,
      isArrearsPayment: false,
      runningBalanceAfter: 55140,
      notes: "Regular monthly payment",
    },
  ],
  loan_003: [
    {
      id: "payment_008",
      loanId: "loan_003",
      transactionId: "txn_301",
      date: "2025-12-01",
      paidAmount: 650,
      principalPortion: 520.0,
      interestPortion: 130.0,
      lateCharges: 0,
      otherCharges: 0,
      isExtraPayment: false,
      isArrearsPayment: false,
      runningBalanceAfter: 8850,
      notes: "Regular monthly payment",
    },
  ],
};

export const mockIOUs: IOU[] = [
  {
    id: "iou_001",
    personName: "Bryan",
    direction: "I_OWE",
    amount: 45.0,
    description: "Pizza night at Kenny Rogers",
    date: "2025-12-08",
    status: "PENDING",
    notes: "He paid for both of us, will settle next week",
  },
  {
    id: "iou_002",
    personName: "Alan",
    direction: "OWES_ME",
    amount: 15.5,
    description: "Coffee at Starbucks",
    date: "2025-12-10",
    status: "PENDING",
    notes: "Bought him coffee, forgot wallet",
  },
  {
    id: "iou_003",
    personName: "Sarah",
    direction: "I_OWE",
    amount: 120.0,
    description: "Concert tickets - Taylor Swift",
    date: "2025-11-20",
    transactionId: "txn_450",
    status: "SETTLED",
    notes: "Paid back on Dec 1st",
  },
  {
    id: "iou_004",
    personName: "Mike",
    direction: "OWES_ME",
    amount: 80.0,
    description: "Lunch bill - team outing",
    date: "2025-12-05",
    status: "PENDING",
    notes: "Group lunch, he'll transfer by end of month",
  },
  {
    id: "iou_005",
    personName: "Jessica",
    direction: "OWES_ME",
    amount: 250.0,
    description: "Advance for trip expenses",
    date: "2025-11-15",
    transactionId: "txn_451",
    status: "SETTLED",
    notes: "Settled via bank transfer",
  },
];
