// file: lib/mock-data.ts
// Mock data for NvjmiOS 2.0 - TODO: Replace with real API calls

import {
  MoneyTransaction,
  LifeEvent,
  Task,
  Module,
  WishlistItem,
  BNPLItem,
  SavingsGoal,
  Debt,
  HealthMetric,
  FoodLogEntry,
  Habit,
  TimeEntry,
  Project,
  KnowledgeNote,
  Meeting,
  Document,
  Expense,
  Purchase,
  BankStatement,
  Agreement,
  Receipt,
  Account,
  InboxItem,
} from "./types";

// TODO: Replace with API call to /api/transactions
export const mockTransactions: MoneyTransaction[] = [
  {
    id: "txn_001",
    date: "2025-12-07",
    description: "Lunch at Nasi Kandar",
    category: "Food",
    amount: -18.5,
    account: "Maybank",
    tags: ["food", "lunch"],
    notes: "Team lunch",
  },
  {
    id: "txn_002",
    date: "2025-12-06",
    description: "Grab to office",
    category: "Transport",
    amount: -12.0,
    account: "Touch 'n Go",
    tags: ["transport", "work"],
  },
  {
    id: "txn_003",
    date: "2025-12-05",
    description: "Monthly Salary",
    category: "Salary",
    amount: 5500.0,
    account: "Maybank",
    tags: ["income", "salary"],
  },
  {
    id: "txn_004",
    date: "2025-12-04",
    description: "Shopee purchase - Monitor",
    category: "Shopping",
    amount: -680.0,
    account: "Maybank",
    tags: ["electronics", "work-setup"],
    linkedEvents: ["evt_001"],
  },
  {
    id: "txn_005",
    date: "2025-12-03",
    description: "Electricity bill",
    category: "Bills",
    amount: -125.3,
    account: "Maybank",
    tags: ["utilities", "bills"],
  },
  {
    id: "txn_006",
    date: "2025-12-02",
    description: "Coffee at VCR",
    category: "Food",
    amount: -14.5,
    account: "Maybank",
    tags: ["coffee", "cafe"],
  },
  {
    id: "txn_007",
    date: "2025-12-01",
    description: "Gym membership",
    category: "Health",
    amount: -150.0,
    account: "Maybank",
    tags: ["health", "gym", "subscription"],
  },
];

// TODO: Replace with API call to /api/life-events
export const mockLifeEvents: LifeEvent[] = [
  {
    id: "evt_001",
    title: "Set up home office workspace",
    date: "2025-12-04",
    type: "Work",
    importance: 4,
    description:
      "Finally invested in a proper monitor and ergonomic setup for remote work",
    notes: "Bought 27-inch monitor, adjustable desk lamp, and standing desk converter",
    linkedTransactions: ["txn_004"],
    tags: ["home-office", "productivity"],
  },
  {
    id: "evt_002",
    title: "Started new fitness routine",
    date: "2025-12-01",
    type: "Health",
    importance: 5,
    description:
      "Committed to going to the gym 3x per week. Day 1 done!",
    reflection:
      "Felt great after the workout. Need to track consistency and measure progress over time.",
    linkedTransactions: ["txn_007"],
    tags: ["health", "fitness", "goals"],
  },
  {
    id: "evt_003",
    title: "Completed Q4 Performance Review",
    date: "2025-11-28",
    type: "Work",
    importance: 4,
    description: "Annual performance review with manager - exceeded expectations",
    notes: "Discussed promotion path and salary adjustment for next year",
    linkedTasks: ["tsk_001"],
    tags: ["career", "review"],
  },
  {
    id: "evt_004",
    title: "Weekend trip to Penang",
    date: "2025-11-15",
    type: "Travel",
    importance: 3,
    description: "Short getaway to Penang with friends",
    tags: ["travel", "friends"],
  },
];

// TODO: Replace with API call to /api/tasks
export const mockTasks: Task[] = [
  {
    id: "tsk_001",
    title: "Prepare DR (Disaster Recovery) documentation",
    description: "Document all system recovery procedures",
    status: "in_progress",
    priority: "high",
    dueDate: "2025-12-15",
    project: "Infrastructure",
    tags: ["docs", "devops"],
    linkedEvents: ["evt_003"],
    createdAt: "2025-11-20",
    updatedAt: "2025-12-05",
  },
  {
    id: "tsk_002",
    title: "Review and approve team's Q1 OKRs",
    description: "Review objectives and key results for Q1 2026",
    status: "todo",
    priority: "medium",
    dueDate: "2025-12-20",
    project: "Management",
    tags: ["planning", "okr"],
    createdAt: "2025-12-01",
    updatedAt: "2025-12-01",
  },
  {
    id: "tsk_003",
    title: "Fix authentication bug in production",
    status: "done",
    priority: "urgent",
    project: "Backend",
    tags: ["bug", "auth"],
    createdAt: "2025-11-28",
    updatedAt: "2025-11-29",
  },
  {
    id: "tsk_004",
    title: "Plan December team offsite",
    description: "Book venue and plan activities for team building",
    status: "todo",
    priority: "medium",
    dueDate: "2025-12-10",
    project: "Team",
    tags: ["team", "planning"],
    createdAt: "2025-12-02",
    updatedAt: "2025-12-02",
  },
];

// Module tree structure for sidebar
export const moduleTree: Module[] = [
  {
    id: "today",
    name: "Today",
    path: "/",
  },
  {
    id: "calendar",
    name: "Calendar",
    path: "/calendar",
  },
  {
    id: "inbox",
    name: "Inbox",
    path: "/inbox",
  },
  {
    id: "money",
    name: "Money",
    path: "/money",
    subModules: [
      { id: "money-overview", name: "Overview", path: "/money" },
      { id: "accounts", name: "Accounts", path: "/money/accounts" },
      { id: "transactions", name: "Transactions", path: "/money/transactions" },
      { id: "bnpl", name: "BNPL", path: "/money/bnpl" },
      { id: "savings", name: "Savings", path: "/money/savings" },
      { id: "debts", name: "Debts", path: "/money/debts" },
      { id: "wishlist", name: "Wishlist", path: "/money/wishlist" },
    ],
  },
  {
    id: "life",
    name: "Life",
    path: "/life",
    subModules: [
      { id: "events", name: "Events", path: "/life/events" },
      { id: "health", name: "Health", path: "/life/health" },
      { id: "habits", name: "Habits", path: "/life/habits" },
      { id: "food", name: "Food Log", path: "/life/food" },
      { id: "time", name: "Time Log", path: "/life/time" },
    ],
  },
  {
    id: "work",
    name: "Work",
    path: "/work",
    subModules: [
      { id: "tasks", name: "Tasks", path: "/work/tasks" },
      { id: "projects", name: "Projects", path: "/work/projects" },
      { id: "meetings", name: "Meetings", path: "/work/meetings" },
      { id: "knowledge", name: "Knowledge", path: "/work/knowledge" },
    ],
  },
  {
    id: "documents",
    name: "Documents",
    path: "/documents",
    subModules: [
      { id: "salary", name: "Salary Slips", path: "/documents/salary" },
      { id: "statements", name: "Statements", path: "/documents/statements" },
      { id: "agreements", name: "Agreements", path: "/documents/agreements" },
      { id: "receipts", name: "Receipts", path: "/documents/receipts" },
    ],
  },
  {
    id: "settings",
    name: "Settings",
    path: "/settings",
  },
];

// TODO: Replace with API call to /api/wishlist
export const mockWishlistItems: WishlistItem[] = [
  {
    id: "wish_001",
    name: "Sony WH-1000XM5 Headphones",
    description: "Noise-cancelling headphones for focused work",
    estimatedCost: 1599,
    priority: 4,
    status: "researching",
    category: "Electronics",
    url: "https://www.sony.com.my/electronics/headband-headphones/wh-1000xm5",
    savedAmount: 400,
    targetDate: "2026-01-15",
    createdAt: "2025-11-20",
    tags: ["tech", "productivity", "audio"],
  },
  {
    id: "wish_002",
    name: "Standing Desk",
    description: "Ergonomic electric standing desk",
    estimatedCost: 2500,
    priority: 5,
    status: "saved_for",
    category: "Furniture",
    savedAmount: 2100,
    targetDate: "2025-12-31",
    createdAt: "2025-10-01",
    tags: ["furniture", "health", "workspace"],
  },
  {
    id: "wish_003",
    name: "Weekend trip to Japan",
    estimatedCost: 8000,
    priority: 3,
    status: "wishlist",
    category: "Travel",
    savedAmount: 1200,
    targetDate: "2026-06-01",
    createdAt: "2025-09-15",
    tags: ["travel", "vacation"],
    notes: "Cherry blossom season",
  },
];

// TODO: Replace with API call to /api/bnpl
export const mockBNPLItems: BNPLItem[] = [
  {
    id: "bnpl_001",
    merchant: "Shopee",
    item: "iPhone 15 Pro",
    totalAmount: 5299,
    paidAmount: 2649.50,
    remainingAmount: 2649.50,
    installments: 6,
    installmentsPaid: 3,
    monthlyPayment: 883.17,
    nextPaymentDate: "2025-12-15",
    status: "active",
    provider: "SPayLater",
    startDate: "2025-09-15",
    tags: ["tech", "phone"],
  },
  {
    id: "bnpl_002",
    merchant: "Harvey Norman",
    item: "LG 55\" OLED TV",
    totalAmount: 3999,
    paidAmount: 3999,
    remainingAmount: 0,
    installments: 12,
    installmentsPaid: 12,
    monthlyPayment: 333.25,
    nextPaymentDate: "2025-11-30",
    status: "completed",
    provider: "Atome",
    startDate: "2024-12-01",
    tags: ["electronics", "home"],
  },
];

// TODO: Replace with API call to /api/savings
export const mockSavingsGoals: SavingsGoal[] = [
  {
    id: "sav_001",
    name: "Emergency Fund",
    targetAmount: 30000,
    currentAmount: 18500,
    category: "Emergency",
    monthlyContribution: 1500,
    notes: "6 months of expenses",
    createdAt: "2024-01-01",
    tags: ["emergency", "essential"],
  },
  {
    id: "sav_002",
    name: "Japan Trip 2026",
    targetAmount: 8000,
    currentAmount: 1200,
    category: "Travel",
    targetDate: "2026-06-01",
    monthlyContribution: 500,
    createdAt: "2025-09-15",
    tags: ["travel", "vacation"],
  },
  {
    id: "sav_003",
    name: "New Car Down Payment",
    targetAmount: 20000,
    currentAmount: 5000,
    category: "Vehicle",
    targetDate: "2026-12-31",
    monthlyContribution: 1000,
    createdAt: "2025-06-01",
    tags: ["car", "transportation"],
  },
];

// TODO: Replace with API call to /api/debts
export const mockDebts: Debt[] = [
  {
    id: "debt_001",
    name: "Car Loan - Honda Civic",
    type: "car_loan",
    totalAmount: 80000,
    paidAmount: 32000,
    remainingAmount: 48000,
    interestRate: 2.5,
    monthlyPayment: 1600,
    nextPaymentDate: "2025-12-15",
    status: "active",
    creditor: "Maybank",
    startDate: "2023-08-01",
    tags: ["car", "loan"],
  },
  {
    id: "debt_002",
    name: "Credit Card - CIMB Visa",
    type: "credit_card",
    totalAmount: 8500,
    paidAmount: 3200,
    remainingAmount: 5300,
    interestRate: 18.0,
    monthlyPayment: 500,
    nextPaymentDate: "2025-12-05",
    status: "active",
    creditor: "CIMB Bank",
    startDate: "2024-06-01",
    notes: "Accumulated from home renovation",
    tags: ["credit-card", "renovation"],
  },
];

// TODO: Replace with API call to /api/health
export const mockHealthMetrics: HealthMetric[] = [
  {
    id: "health_001",
    date: "2025-12-07",
    weight: 72.5,
    sleepHours: 7.5,
    steps: 8500,
    waterIntake: 2.2,
    mood: "good",
    energy: 4,
    notes: "Good workout day",
    tags: ["gym", "active"],
  },
  {
    id: "health_002",
    date: "2025-12-06",
    weight: 72.8,
    sleepHours: 6.2,
    steps: 5200,
    waterIntake: 1.8,
    mood: "okay",
    energy: 3,
    tags: ["work-heavy"],
  },
  {
    id: "health_003",
    date: "2025-12-05",
    weight: 73.0,
    sleepHours: 8.0,
    steps: 12000,
    waterIntake: 2.5,
    mood: "great",
    energy: 5,
    notes: "Weekend hike, feeling amazing",
    tags: ["hiking", "outdoor"],
  },
];

// TODO: Replace with API call to /api/food-log
export const mockFoodLog: FoodLogEntry[] = [
  {
    id: "food_001",
    date: "2025-12-07",
    time: "08:30",
    mealType: "breakfast",
    description: "Oatmeal with banana and honey",
    calories: 350,
    protein: 8,
    carbs: 65,
    fats: 6,
    waterIntake: 0.5,
    tags: ["healthy", "home"],
  },
  {
    id: "food_002",
    date: "2025-12-07",
    time: "13:00",
    mealType: "lunch",
    description: "Nasi lemak with chicken",
    location: "Village Park Restaurant",
    calories: 650,
    protein: 35,
    carbs: 80,
    fats: 28,
    mood: "satisfied",
    waterIntake: 0.3,
    tags: ["local", "restaurant"],
  },
  {
    id: "food_003",
    date: "2025-12-07",
    time: "19:30",
    mealType: "dinner",
    description: "Grilled salmon with vegetables",
    location: "Home",
    calories: 550,
    protein: 42,
    carbs: 35,
    fats: 25,
    waterIntake: 0.4,
    notes: "Meal prep Sunday batch",
    tags: ["healthy", "home", "meal-prep"],
  },
  {
    id: "food_004",
    date: "2025-12-06",
    time: "07:45",
    mealType: "breakfast",
    description: "Scrambled eggs with toast",
    location: "Home",
    calories: 420,
    protein: 24,
    carbs: 38,
    fats: 18,
    mood: "neutral",
    waterIntake: 0.3,
    tags: ["home", "quick"],
  },
  {
    id: "food_005",
    date: "2025-12-06",
    time: "12:30",
    mealType: "lunch",
    description: "Chicken rice with soup",
    location: "Tian Tian Chicken Rice",
    calories: 580,
    protein: 38,
    carbs: 72,
    fats: 16,
    mood: "satisfied",
    waterIntake: 0.2,
    tags: ["local", "chicken-rice"],
  },
  {
    id: "food_006",
    date: "2025-12-06",
    time: "15:30",
    mealType: "snack",
    description: "Protein shake",
    location: "Office",
    calories: 180,
    protein: 25,
    carbs: 12,
    fats: 4,
    waterIntake: 0.5,
    tags: ["protein", "post-workout"],
  },
  {
    id: "food_007",
    date: "2025-12-06",
    time: "19:00",
    mealType: "dinner",
    description: "Pasta carbonara",
    location: "Home",
    calories: 720,
    protein: 28,
    carbs: 82,
    fats: 32,
    mood: "great",
    notes: "Made from scratch, very tasty",
    waterIntake: 0.3,
    tags: ["home", "italian", "cooking"],
  },
  {
    id: "food_008",
    date: "2025-12-05",
    time: "08:00",
    mealType: "breakfast",
    description: "Greek yogurt with berries and granola",
    location: "Home",
    calories: 380,
    protein: 18,
    carbs: 55,
    fats: 10,
    mood: "good",
    waterIntake: 0.2,
    tags: ["healthy", "home", "breakfast"],
  },
  {
    id: "food_009",
    date: "2025-12-05",
    time: "13:15",
    mealType: "lunch",
    description: "Burger and fries",
    location: "MyBurgerLab",
    calories: 920,
    protein: 42,
    carbs: 88,
    fats: 48,
    mood: "satisfied",
    notes: "Weekend treat!",
    waterIntake: 0.4,
    tags: ["restaurant", "cheat-meal"],
  },
];

// TODO: Replace with API call to /api/habits
export const mockHabits: Habit[] = [
  {
    id: "habit_001",
    name: "Morning Exercise",
    description: "30 minutes of exercise every morning",
    frequency: "daily",
    targetCount: 7,
    color: "#10b981",
    currentStreak: 12,
    longestStreak: 28,
    completedDates: ["2025-12-07", "2025-12-06", "2025-12-05", "2025-12-04"],
    createdAt: "2025-11-01",
    tags: ["health", "fitness"],
  },
  {
    id: "habit_002",
    name: "Read 30 minutes",
    description: "Reading before bed",
    frequency: "daily",
    targetCount: 7,
    color: "#3b82f6",
    currentStreak: 5,
    longestStreak: 15,
    completedDates: ["2025-12-07", "2025-12-06", "2025-12-05"],
    createdAt: "2025-10-15",
    tags: ["learning", "personal"],
  },
  {
    id: "habit_003",
    name: "Weekly Review",
    description: "Review goals and plans for the week",
    frequency: "weekly",
    targetCount: 1,
    color: "#8b5cf6",
    currentStreak: 8,
    longestStreak: 12,
    completedDates: ["2025-12-01", "2025-11-24"],
    createdAt: "2025-09-01",
    tags: ["planning", "productivity"],
  },
];

// TODO: Replace with API call to /api/time-tracking
export const mockTimeEntries: TimeEntry[] = [
  {
    id: "time_001",
    date: "2025-12-07",
    startTime: "09:00",
    endTime: "12:30",
    duration: 210,
    category: "work",
    description: "Feature development - User authentication",
    project: "Main Product",
    billable: true,
    tags: ["development", "backend"],
  },
  {
    id: "time_002",
    date: "2025-12-07",
    startTime: "14:00",
    endTime: "16:00",
    duration: 120,
    category: "work",
    description: "Team meeting and code review",
    project: "Main Product",
    billable: false,
    tags: ["meeting", "collaboration"],
  },
  {
    id: "time_003",
    date: "2025-12-07",
    startTime: "19:00",
    endTime: "20:30",
    duration: 90,
    category: "learning",
    description: "Learning Next.js 15 features",
    billable: false,
    tags: ["learning", "nextjs"],
  },
  {
    id: "time_004",
    date: "2025-12-06",
    startTime: "09:30",
    endTime: "13:00",
    duration: 210,
    category: "work",
    description: "API integration with payment gateway",
    project: "Main Product",
    billable: true,
    notes: "Integrated Stripe payment flow",
    tags: ["development", "integration"],
  },
  {
    id: "time_005",
    date: "2025-12-06",
    startTime: "14:30",
    endTime: "15:30",
    duration: 60,
    category: "work",
    description: "Sprint planning meeting",
    project: "Infrastructure Upgrade",
    billable: false,
    tags: ["meeting", "planning"],
  },
  {
    id: "time_006",
    date: "2025-12-06",
    startTime: "16:00",
    endTime: "18:00",
    duration: 120,
    category: "work",
    description: "Bug fixes and testing",
    project: "Main Product",
    billable: true,
    tags: ["bug-fix", "testing"],
  },
  {
    id: "time_007",
    date: "2025-12-06",
    startTime: "20:00",
    endTime: "21:00",
    duration: 60,
    category: "personal",
    description: "Working on personal portfolio",
    project: "Personal Portfolio Website",
    billable: false,
    tags: ["personal", "web-dev"],
  },
  {
    id: "time_008",
    date: "2025-12-05",
    startTime: "10:00",
    endTime: "12:00",
    duration: 120,
    category: "work",
    description: "Database optimization and query tuning",
    project: "Infrastructure Upgrade",
    billable: true,
    tags: ["database", "optimization"],
  },
  {
    id: "time_009",
    date: "2025-12-05",
    startTime: "14:00",
    endTime: "17:00",
    duration: 180,
    category: "work",
    description: "Frontend component development",
    project: "Main Product",
    billable: true,
    notes: "Built new dashboard components",
    tags: ["frontend", "react"],
  },
  {
    id: "time_010",
    date: "2025-12-05",
    startTime: "18:00",
    endTime: "19:30",
    duration: 90,
    category: "learning",
    description: "Reading TypeScript design patterns",
    billable: false,
    tags: ["learning", "typescript"],
  },
];

// TODO: Replace with API call to /api/projects
export const mockProjects: Project[] = [
  {
    id: "proj_001",
    name: "Main Product v2.0",
    description: "Major product overhaul with new features",
    status: "active",
    progress: 65,
    startDate: "2025-09-01",
    endDate: "2026-03-31",
    nextMilestone: "Beta Release - Dec 2025",
    team: ["John", "Sarah", "Mike"],
    tags: ["product", "high-priority"],
    linkedTasks: ["tsk_001", "tsk_002"],
    createdAt: "2025-08-15",
    updatedAt: "2025-12-07",
  },
  {
    id: "proj_002",
    name: "Infrastructure Upgrade",
    description: "Migrate to Kubernetes and improve CI/CD",
    status: "active",
    progress: 40,
    startDate: "2025-10-01",
    endDate: "2026-01-31",
    nextMilestone: "K8s cluster setup",
    team: ["Mike", "Alex"],
    tags: ["infrastructure", "devops"],
    linkedTasks: ["tsk_001"],
    createdAt: "2025-09-20",
    updatedAt: "2025-12-05",
  },
  {
    id: "proj_003",
    name: "Personal Portfolio Website",
    description: "New portfolio showcasing projects and writing",
    status: "planning",
    progress: 10,
    startDate: "2025-12-01",
    tags: ["personal", "website"],
    createdAt: "2025-11-28",
    updatedAt: "2025-12-03",
  },
];

// TODO: Replace with API call to /api/knowledge
export const mockKnowledgeNotes: KnowledgeNote[] = [
  {
    id: "note_001",
    title: "Next.js 15 App Router Patterns",
    content: "# Server Components vs Client Components\n\nKey differences and when to use each...",
    category: "Development",
    tags: ["nextjs", "react", "web-dev"],
    linkedNotes: ["note_002"],
    createdAt: "2025-12-05",
    updatedAt: "2025-12-07",
  },
  {
    id: "note_002",
    title: "TypeScript Best Practices",
    content: "## Type Safety Patterns\n\n1. Use strict mode\n2. Avoid 'any' type...",
    category: "Development",
    tags: ["typescript", "coding"],
    linkedNotes: ["note_001"],
    createdAt: "2025-11-20",
    updatedAt: "2025-11-25",
  },
  {
    id: "note_003",
    title: "Team Management Insights",
    content: "Key learnings from managing a remote team...",
    category: "Management",
    tags: ["leadership", "team", "remote"],
    createdAt: "2025-10-15",
    updatedAt: "2025-11-30",
  },
];

// TODO: Replace with API call to /api/meetings
export const mockMeetings: Meeting[] = [
  {
    id: "meet_001",
    title: "Sprint Planning - Q1 2026",
    date: "2025-12-09",
    startTime: "10:00",
    endTime: "11:30",
    attendees: ["John", "Sarah", "Mike", "Alex"],
    location: "Zoom",
    project: "Main Product v2.0",
    agenda: "Plan Q1 sprints and set OKRs",
    notes: "Agreed on 3 major features for Q1",
    status: "planned",
    decisions: [
      "Focus on mobile experience for Q1",
      "Allocate 2 sprints for infrastructure work",
    ],
    actionItems: [
      { id: "ai_001", task: "Draft Q1 roadmap", assignee: "John", done: false },
      { id: "ai_002", task: "Set up project boards", assignee: "Sarah", done: false },
    ],
    linkedTasks: ["tsk_002"],
    tags: ["planning", "sprint"],
  },
  {
    id: "meet_002",
    title: "1-on-1 with Manager",
    date: "2025-12-08",
    startTime: "14:00",
    endTime: "14:30",
    attendees: ["Manager", "Me"],
    location: "Office - Meeting Room 2",
    notes: "Discussed career progression and 2026 goals",
    status: "completed",
    actionItems: [
      { id: "ai_003", task: "Draft career development plan", assignee: "Me", done: true },
    ],
    tags: ["1-on-1", "career"],
  },
  {
    id: "meet_003",
    title: "Client Demo - Product v2.0",
    date: "2025-12-10",
    startTime: "15:00",
    endTime: "16:00",
    attendees: ["Client Team", "Sales", "Product"],
    location: "Zoom",
    project: "Main Product v2.0",
    agenda: "Showcase new features and gather feedback",
    status: "planned",
    tags: ["demo", "client"],
  },
  {
    id: "meet_004",
    title: "Team Retrospective - Nov 2025",
    date: "2025-12-02",
    startTime: "16:00",
    endTime: "17:00",
    attendees: ["Full Team"],
    location: "Office - Meeting Room 1",
    notes: "Good month overall, identified process improvements",
    status: "completed",
    decisions: [
      "Move to 2-week sprints instead of 1-week",
      "Add code review checklist",
    ],
    actionItems: [
      { id: "ai_004", task: "Create code review checklist", assignee: "Tech Lead", done: true },
      { id: "ai_005", task: "Update sprint cadence in Jira", assignee: "PM", done: false },
    ],
    tags: ["retrospective", "team"],
  },
];

// TODO: Replace with API call to /api/documents
export const mockDocuments: Document[] = [
  {
    id: "doc_001",
    title: "November 2025 Salary Slip",
    type: "salary_slip",
    date: "2025-11-30",
    tags: ["salary", "2025"],
    linkedTransactions: ["txn_003"],
  },
  {
    id: "doc_002",
    title: "Maybank Statement - Nov 2025",
    type: "bank_statement",
    date: "2025-11-30",
    tags: ["maybank", "statement", "2025"],
  },
  {
    id: "doc_003",
    title: "Rental Agreement - Condo",
    type: "agreement",
    date: "2024-01-01",
    tags: ["rental", "housing", "agreement"],
  },
  {
    id: "doc_004",
    title: "Shopee Receipt - Monitor",
    type: "receipt",
    date: "2025-12-04",
    tags: ["receipt", "electronics"],
    linkedTransactions: ["txn_004"],
    linkedEvents: ["evt_001"],
  },
];

// TODO: Replace with API call to /api/expenses
export const mockExpenses: import("./types").Expense[] = [
  {
    id: "exp_001",
    date: "2025-12-07",
    description: "Lunch at Nasi Kandar",
    category: "Food",
    amount: 18.5,
    account: "Maybank",
    tags: ["food", "lunch"],
    notes: "Team lunch",
    percentOfMonthly: 2.5,
  },
  {
    id: "exp_002",
    date: "2025-12-06",
    description: "Grab to office",
    category: "Transport",
    amount: 12.0,
    account: "Touch 'n Go",
    tags: ["transport", "work"],
    percentOfMonthly: 1.6,
  },
  {
    id: "exp_003",
    date: "2025-12-04",
    description: "Shopee purchase - Monitor",
    category: "Shopping",
    amount: 680.0,
    account: "Maybank",
    tags: ["electronics", "work-setup"],
    percentOfMonthly: 91.9,
    linkedTransactions: ["txn_004"],
  },
  {
    id: "exp_004",
    date: "2025-12-03",
    description: "Electricity bill",
    category: "Bills",
    amount: 125.3,
    account: "Maybank",
    tags: ["utilities", "bills"],
    percentOfMonthly: 16.9,
  },
  {
    id: "exp_005",
    date: "2025-12-02",
    description: "Coffee at VCR",
    category: "Food",
    amount: 14.5,
    account: "Maybank",
    tags: ["coffee", "cafe"],
    percentOfMonthly: 2.0,
  },
  {
    id: "exp_006",
    date: "2025-12-01",
    description: "Gym membership",
    category: "Health",
    amount: 150.0,
    account: "Maybank",
    tags: ["health", "gym", "subscription"],
    notes: "Monthly recurring",
    percentOfMonthly: 20.3,
  },
  {
    id: "exp_007",
    date: "2025-11-28",
    description: "Groceries at Jaya Grocer",
    category: "Food",
    amount: 245.0,
    account: "Maybank",
    tags: ["groceries", "food"],
    percentOfMonthly: 33.1,
  },
];

// TODO: Replace with API call to /api/purchases
export const mockPurchases: import("./types").Purchase[] = [
  {
    id: "pur_001",
    item: "Dell UltraSharp 27\" Monitor",
    category: "Electronics",
    store: "Shopee",
    cost: 1299.0,
    status: "completed",
    purchasedOn: "2025-12-04",
    warrantyUntil: "2026-12-04",
    notes: "For home office setup",
    linkedDocuments: ["doc_004"],
    tags: ["work", "electronics"],
  },
  {
    id: "pur_002",
    item: "Sony WH-1000XM5 Headphones",
    category: "Electronics",
    store: "Harvey Norman",
    cost: 1599.0,
    status: "ordered",
    purchasedOn: "2025-12-05",
    warrantyUntil: "2026-12-05",
    tags: ["electronics", "audio"],
  },
  {
    id: "pur_003",
    item: "Standing Desk Frame",
    category: "Furniture",
    store: "IKEA",
    cost: 899.0,
    status: "delivered",
    purchasedOn: "2025-11-20",
    warrantyUntil: "2030-11-20",
    notes: "Waiting for tabletop installation",
    tags: ["furniture", "workspace"],
  },
  {
    id: "pur_004",
    item: "Mechanical Keyboard - Keychron K8",
    category: "Electronics",
    store: "Lazada",
    cost: 399.0,
    status: "completed",
    purchasedOn: "2025-11-15",
    warrantyUntil: "2026-11-15",
    tags: ["electronics", "peripherals"],
  },
  {
    id: "pur_005",
    item: "Ergonomic Office Chair",
    category: "Furniture",
    store: "Courts",
    cost: 1299.0,
    status: "wishlist",
    notes: "Considering Secretlab TITAN Evo",
    tags: ["furniture", "workspace"],
  },
];

// TODO: Replace with API call to /api/bank-statements
export const mockBankStatements: import("./types").BankStatement[] = [
  {
    id: "stmt_001",
    title: "Maybank Statement - December 2025",
    account: "Maybank Savings (****1234)",
    period: "Dec 2025",
    startDate: "2025-12-01",
    endDate: "2025-12-07",
    fileType: "PDF",
    fileSize: "2.4 MB",
    uploadedOn: "2025-12-07",
    status: "parsed",
    transactionCount: 42,
    linkedTransactions: ["txn_001", "txn_002", "txn_003"],
    tags: ["maybank", "2025", "savings"],
  },
  {
    id: "stmt_002",
    title: "Maybank Statement - November 2025",
    account: "Maybank Savings (****1234)",
    period: "Nov 2025",
    startDate: "2025-11-01",
    endDate: "2025-11-30",
    fileType: "PDF",
    fileSize: "3.1 MB",
    uploadedOn: "2025-12-01",
    status: "parsed",
    transactionCount: 87,
    tags: ["maybank", "2025", "savings"],
  },
  {
    id: "stmt_003",
    title: "CIMB Credit Card Statement - November 2025",
    account: "CIMB Visa (****5678)",
    period: "Nov 2025",
    startDate: "2025-11-01",
    endDate: "2025-11-30",
    fileType: "PDF",
    fileSize: "1.8 MB",
    uploadedOn: "2025-12-01",
    status: "parsed",
    transactionCount: 34,
    tags: ["cimb", "credit-card", "2025"],
  },
  {
    id: "stmt_004",
    title: "Touch 'n Go eWallet - October 2025",
    account: "TNG eWallet",
    period: "Oct 2025",
    startDate: "2025-10-01",
    endDate: "2025-10-31",
    fileType: "CSV",
    fileSize: "156 KB",
    uploadedOn: "2025-11-05",
    status: "uploaded",
    transactionCount: 52,
    tags: ["tng", "ewallet", "2025"],
  },
];

// TODO: Replace with API call to /api/agreements
export const mockAgreements: import("./types").Agreement[] = [
  {
    id: "agr_001",
    title: "Condo Rental Agreement - Damansara Heights",
    type: "rental",
    counterparty: "Property Owner - Mr. Tan",
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    status: "active",
    renewalDate: "2026-10-01",
    monthlyPayment: 2800.0,
    importantClauses: [
      "2 months notice required for early termination",
      "Deposit: 3 months rental (RM 8,400)",
      "Utilities excluded",
    ],
    notes: "Excellent location, near LRT station",
    linkedDocuments: ["doc_003"],
    tags: ["rental", "housing", "active"],
  },
  {
    id: "agr_002",
    title: "Car Loan Agreement - Honda Civic",
    type: "loan",
    counterparty: "Maybank",
    startDate: "2023-08-01",
    endDate: "2032-07-31",
    status: "active",
    monthlyPayment: 1600.0,
    importantClauses: [
      "9-year tenure",
      "Interest rate: 2.5% p.a.",
      "Early settlement penalty: 2% of outstanding balance",
    ],
    tags: ["loan", "car", "active"],
  },
  {
    id: "agr_003",
    title: "Freelance Service Agreement - Client XYZ",
    type: "service",
    counterparty: "XYZ Sdn Bhd",
    startDate: "2025-10-01",
    endDate: "2026-09-30",
    status: "active",
    importantClauses: [
      "30 hours per month minimum",
      "Rate: RM 150/hour",
      "Payment within 15 days of invoice",
    ],
    notes: "Annual contract, renewable",
    tags: ["freelance", "service", "active"],
  },
  {
    id: "agr_004",
    title: "Internet Service - TIME Fiber 500Mbps",
    type: "service",
    counterparty: "TIME dotCom",
    startDate: "2024-06-01",
    endDate: "2026-05-31",
    status: "active",
    monthlyPayment: 139.0,
    importantClauses: [
      "24-month contract",
      "Early termination: RM 500",
      "Free installation",
    ],
    tags: ["internet", "utilities", "active"],
  },
  {
    id: "agr_005",
    title: "Previous Employment Contract - TechCorp",
    type: "employment",
    counterparty: "TechCorp Sdn Bhd",
    startDate: "2020-03-01",
    endDate: "2024-08-31",
    status: "terminated",
    notes: "Left for current role",
    tags: ["employment", "expired"],
  },
];

// TODO: Replace with API call to /api/receipts
export const mockReceipts: import("./types").Receipt[] = [
  {
    id: "rcp_001",
    title: "Dell Monitor Purchase",
    category: "Electronics",
    store: "Shopee",
    amount: 1299.0,
    purchasedOn: "2025-12-04",
    warrantyUntil: "2026-12-04",
    linkedPurchase: "pur_001",
    linkedExpense: "exp_003",
    tags: ["electronics", "warranty"],
  },
  {
    id: "rcp_002",
    title: "Groceries - Jaya Grocer",
    category: "Food",
    store: "Jaya Grocer",
    amount: 245.0,
    purchasedOn: "2025-11-28",
    linkedExpense: "exp_007",
    tags: ["groceries", "food"],
  },
  {
    id: "rcp_003",
    title: "Gym Membership - Dec 2025",
    category: "Health",
    store: "Fitness First",
    amount: 150.0,
    purchasedOn: "2025-12-01",
    linkedExpense: "exp_006",
    tags: ["gym", "recurring"],
  },
  {
    id: "rcp_004",
    title: "Standing Desk Frame",
    category: "Furniture",
    store: "IKEA",
    amount: 899.0,
    purchasedOn: "2025-11-20",
    warrantyUntil: "2030-11-20",
    linkedPurchase: "pur_003",
    tags: ["furniture", "warranty"],
  },
  {
    id: "rcp_005",
    title: "Keychron K8 Keyboard",
    category: "Electronics",
    store: "Lazada",
    amount: 399.0,
    purchasedOn: "2025-11-15",
    warrantyUntil: "2026-11-15",
    linkedPurchase: "pur_004",
    tags: ["electronics", "warranty"],
  },
];

// TODO: Replace with API call to /api/accounts
export const mockAccounts: Account[] = [
  {
    id: "acc_001",
    name: "Maybank Savings",
    type: "bank",
    balance: 12450.75,
    notes: "Primary savings account",
    tags: ["savings", "primary"],
  },
  {
    id: "acc_002",
    name: "Touch n Go eWallet",
    type: "ewallet",
    balance: 245.30,
    notes: "For transport and parking",
    tags: ["ewallet", "transport"],
  },
  {
    id: "acc_003",
    name: "Shopee PayLater",
    type: "bnpl",
    balance: -850.00,
    limit: 3000.00,
    billingDay: 1,
    notes: "Monthly BNPL service",
    tags: ["bnpl", "shopee"],
  },
  {
    id: "acc_004",
    name: "Atome",
    type: "bnpl",
    balance: -450.00,
    limit: 2000.00,
    notes: "3-month installment plan",
    tags: ["bnpl", "atome"],
  },
  {
    id: "acc_005",
    name: "HSBC Credit Card",
    type: "card",
    balance: -2340.50,
    limit: 10000.00,
    billingDay: 15,
    notes: "Main credit card",
    tags: ["credit", "card"],
  },
  {
    id: "acc_006",
    name: "CIMB Current",
    type: "bank",
    balance: 3250.00,
    notes: "Salary account",
    tags: ["salary", "current"],
  },
];

// TODO: Replace with API call to /api/inbox
export const mockInboxItems: InboxItem[] = [
  {
    id: "inbox_001",
    title: "Lunch receipt from Restoran Nasi Kandar",
    content: "RM 18.50 spent on team lunch today. Should track this expense.",
    type: "money",
    status: "inbox",
    capturedAt: "2025-12-08T12:30:00Z",
    tags: ["food", "receipt"],
    suggestedTarget: "Money Transaction",
    attachments: [
      {
        id: "att_001",
        name: "receipt_lunch.jpg",
        type: "image/jpeg",
        size: 245000,
        url: "/uploads/dummy_receipt_1.jpg",
        uploadedAt: "2025-12-08T12:30:00Z",
      },
    ],
  },
  {
    id: "inbox_002",
    title: "Fix authentication bug in production",
    content: "Users are reporting they can't log in with Google OAuth. Need to investigate ASAP.",
    type: "task",
    status: "inbox",
    capturedAt: "2025-12-08T09:15:00Z",
    tags: ["urgent", "bug", "auth"],
    suggestedTarget: "Task",
  },
  {
    id: "inbox_003",
    title: "Client meeting notes",
    content: "Discussed Q1 2026 roadmap. Client wants dark mode and PDF export features. Follow up next week.",
    type: "note",
    status: "inbox",
    capturedAt: "2025-12-07T15:45:00Z",
    tags: ["meeting", "client", "roadmap"],
    suggestedTarget: "Knowledge Note",
  },
  {
    id: "inbox_004",
    title: "Code review for payment gateway integration",
    content: "Spent 2 hours reviewing the new Stripe integration PR. Left comments on error handling.",
    type: "time",
    status: "inbox",
    capturedAt: "2025-12-07T17:00:00Z",
    tags: ["work", "code-review"],
    suggestedTarget: "Time Entry",
  },
  {
    id: "inbox_005",
    title: "Health checkup appointment",
    content: "Annual health screening at Gleneagles Hospital on Dec 15. Remember to fast 8 hours before.",
    type: "life",
    status: "inbox",
    capturedAt: "2025-12-06T10:20:00Z",
    tags: ["health", "appointment"],
    suggestedTarget: "Life Event",
  },
  {
    id: "inbox_006",
    title: "Salary slip November 2025",
    content: "Monthly payslip received. Need to file this for tax purposes.",
    type: "document",
    status: "converted",
    capturedAt: "2025-12-01T08:00:00Z",
    tags: ["salary", "finance"],
    attachments: [
      {
        id: "att_002",
        name: "payslip_nov_2025.pdf",
        type: "application/pdf",
        size: 156000,
        url: "/uploads/dummy_payslip.pdf",
        uploadedAt: "2025-12-01T08:00:00Z",
      },
    ],
    convertedTo: {
      type: "salary_slip",
      id: "doc_sal_001",
      convertedAt: "2025-12-01T09:00:00Z",
    },
  },
  {
    id: "inbox_007",
    title: "Gym membership payment",
    content: "Paid RM 150 for December gym membership at FitLife.",
    type: "money",
    status: "inbox",
    capturedAt: "2025-12-05T07:30:00Z",
    tags: ["health", "recurring"],
    suggestedTarget: "Money Transaction",
    linkedEntity: {
      type: "transaction",
      id: "txn_001",
      title: "FitLife Gym Membership - Dec",
    },
  },
  {
    id: "inbox_008",
    title: "Design system documentation",
    content: "Need to document the new component library patterns we've been using. Include examples and best practices.",
    type: "task",
    status: "inbox",
    capturedAt: "2025-12-04T14:00:00Z",
    tags: ["documentation", "design"],
    suggestedTarget: "Task",
    linkedEntity: {
      type: "task",
      id: "task_003",
      title: "Document component library",
    },
  },
  {
    id: "inbox_009",
    title: "Weekend hike at Bukit Tabur",
    content: "Great hike with friends! 3 hours, beautiful sunrise. Need to log this activity.",
    type: "life",
    status: "inbox",
    capturedAt: "2025-12-03T11:00:00Z",
    tags: ["outdoor", "exercise", "friends"],
    suggestedTarget: "Life Event",
  },
  {
    id: "inbox_010",
    title: "Feature development - User dashboard",
    content: "Built the new user analytics dashboard. Took most of the day but looks great.",
    type: "time",
    status: "inbox",
    capturedAt: "2025-12-02T18:30:00Z",
    tags: ["development", "frontend"],
    suggestedTarget: "Time Entry",
    linkedEntity: {
      type: "timeEntry",
      id: "time_001",
      title: "Dashboard development",
    },
  },
];
